# Generated by Django 2.1.1 on 2018-09-04 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_bleeding', models.DateField()),
                ('segment_number', models.CharField(max_length=10)),
                ('blood_bag_type', models.CharField(choices=[('Single 350', 'Single 350'), ('Single 450', 'Single 450'), ('Double 350', 'Double 350'), ('Double 450', 'Double 450'), ('Triple 350', 'Triple 350'), ('Triple 450', 'Triple 450'), ('Segum 450', 'Segum 450'), ('Segum 450', 'Segum 450')], default='Single 350', max_length=20)),
                ('quantity', models.IntegerField()),
                ('type_of_donation', models.CharField(choices=[('VOL', 'Voluntary'), ('REP', 'Replacement')], default='VOL', max_length=3)),
                ('hb_gram_percent', models.FloatField()),
                ('weight', models.FloatField()),
                ('blood_pressure', models.FloatField()),
                ('pulse', models.FloatField()),
                ('temperature', models.FloatField()),
                ('remarks', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=400)),
                ('date_of_birth', models.DateField()),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1)),
                ('blood_group', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], default='A', max_length=2)),
                ('blood_rh', models.CharField(choices=[('+', 'Positive'), ('-', 'Negative')], default='+', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_entry', models.DateField()),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('telephone', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('address', models.CharField(max_length=400)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1)),
                ('blood_group', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], default='A', max_length=2)),
                ('blood_rh', models.CharField(choices=[('+', 'Positive'), ('-', 'Negative')], default='+', max_length=1)),
                ('remarks', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Serology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('hiv', models.NullBooleanField()),
                ('hbsag', models.NullBooleanField()),
                ('hcv', models.NullBooleanField()),
                ('vdrl', models.NullBooleanField()),
                ('mp', models.NullBooleanField()),
                ('donation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dataview.Donation')),
            ],
        ),
        migrations.AddField(
            model_name='donation',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataview.Donor'),
        ),
        migrations.AddField(
            model_name='donation',
            name='replaced_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dataview.Patient'),
        ),
    ]
